---
- name: Instalar y configurar Apache
  hosts: wordpress
  become: yes # Elevar permisos para ejecutar tareas como root

  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Asegurarse de que Apache esté activo y habilitado
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Reiniciar Apache para aplicar cambios
      service:
        name: apache2
        state: restarted
