---
- name: Desinstalar Apache
  hosts: wordpress
  become: yes

  tasks:
    - name: Detener y deshabilitar el servicio Apache
      service:
        name: apache2
        state: stopped
        enabled: no

    - name: Desinstalar Apache y sus dependencias
      apt:
        name: apache2
        state: absent
        autoremove: yes
        purge: yes

    - name: Eliminar archivos de configuración residuales
      file:
        path: /etc/apache2
        state: absent
